### ISSUE TITLE
Label the root page of the jupyter book as "Home Page" rather than the title of the root page.

### ISSUE THREAD

**Issue by berrli** [coding-for-reproducible-research/CfRR_Courses#103]
Currently, the title that appears in the sidebar menu for the root page is the same as the title for the page itself. However we would like the title in the sidebar menu to simply be "Home Page" rather than the title in the page, which is considerably longer with it currently being: " The Coding for Reproducible Research (CfRR) Training Programme Home Page". The approach of adding a title to the _toc.yml file when defining the root does not appear to work in the same manner as when it is done for other pages in the toc file.

**Comment by sketchkey** [comment]
Looks like a lot of folks just remove the title and use their logo as a homepage link if that's of interest? In the `_config.yml`, you add this to the `html:` section:
`  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar`
I've been having a little look into jupyter books so will let you know if I learn another another option!

**Comment by berrli** [comment]
The title for the home page has been set to "Coding for Reproducible Research (CfRR) Training Programme Home Page" which has a good footprint within the menu on the left making navigation easy.
