### ISSUE TITLE
Citation file not parsing

### ISSUE THREAD

**Issue by sketchkey** [coding-for-reproducible-research/CfRR_Courses#114]
The [cff citation file](https://github.com/coding-for-reproducible-research/CfRR_Courses/blob/9656036ef557430b2460a85db519dd027133f199/CITATION.cff) isn't parsing properly so the citation options don't appear when you click on the 'Cite this repo' button.

Suspect it's something to do with the `Iicense: ` section, as the[ examples in the docs](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#license) suggest it should be one license inline or bullet points for multiple licence types.

P.S. I didn't know about .cff files before — they seem great!

**Comment by berrli** [comment]
Hello @sketchkey Thank you for raising this issue! This has been fixed in the latest commit.
