### ISSUE TITLE
Add cron job to automatically build website every night

### ISSUE THREAD

**Issue by berrli** [coding-for-reproducible-research/CfRR_Courses#136]
With the additional of PR #135 there is python code that will generate markdown content that is based on the date. With this there is a need for the implementation of a cron job that will rebuild and redeploy the website based on the new date.

**Comment by emadellaloggia** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by berrli** [comment]
Implemented in #137
