### ISSUE TITLE
Create a CfRR homepage that forwards to CfRR_Courses

### ISSUE THREAD

**Issue by stephenpcook** [coding-for-reproducible-research/CfRR_Courses#36]
The organisation could do with a base website on <https://coding-for-reproducible-research.github.io/>, even if it just forwards to the [CfRR_Courses](https://coding-for-reproducible-research.github.io/CfRR_Courses) page.

I don't know if there's enough information on [Creating a GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site).

**Comment by berrli** [comment]
This has now been done with another repo in the CfRR organisation [coding-for-reproducible-research.github.io](https://github.com/coding-for-reproducible-research/coding-for-reproducible-research.github.io).
