### ISSUE TITLE
Add a CfRR GitHub README

### ISSUE THREAD

**Issue by stephenpcook** [coding-for-reproducible-research/CfRR_Courses#72]
Create a CfRR readme file under a repository `coding-for-reproducible-research/coding-for-reproducible-research`.  This will be visible on the CfRR GitHub profile page.

In GitHub, if you create repository with the same name as the owning username, any `README.md` file will be displayed on the profile page for that user.  This is called the *profile README* and can be used to give an overview of the profile, along with links and contact details.

See [Managing your profile README](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme).

**Comment by amyheather** [comment]
README suggestions:

* "**License** For more details, visit our [Jupyter Book website](https://coding-for-reproducible-research.github.io/CfRR_Courses/home_page.html)." However, it's a little tricky to identify any information re: License from the website.
* "4. **Contribute**: Follow the guidelines in the `CONTRIBUTING.md` file if you wish to contribute to the repository." This file does not exist in the repository (presuming might want to update to `contributing/` folder?)

**Comment by berrli** [comment]
These changes have now been made with the License for the CfRR_Courses added, and the contribute linked fix. The organisation README is now also added, but is in https://github.com/coding-for-reproducible-research/.github rather than the way it works for a normal github profile.
