### ISSUE TITLE
CfRR_Courses redirect or link from https://coding-for-reproducible-research.github.io

### ISSUE THREAD

**Issue by msaunby** [coding-for-reproducible-research/CfRR_Courses#77]
The homepage for the courses is 

  https://coding-for-reproducible-research.github.io/CfRR_Courses/home_page.html 

but 

  https://coding-for-reproducible-research.github.io/ 

gives a 404 error, which could be misleading.

A redirect from that URL ought to be possible.

**Comment by berrli** [comment]
This has now been achieved with the repo [coding-for-reproducible-research.github.io](https://github.com/coding-for-reproducible-research/coding-for-reproducible-research.github.io)
