### ISSUE TITLE
Add plotting with ggplot2 to the R courses - perhaps an additional session for Working with Data in R?

### ISSUE THREAD

**Issue by Ali-Hudson** [coding-for-reproducible-research/CfRR_Courses#90]
The introductory R course has a section on plotting in base R, but there is no course that includes plotting with ggplot2 despite most people using it for their final plots.

**Comment by berrli** [comment]
Thank you bring this suggestion for new content up, i am closing this issue and moving it into the discussion section of the repo along with the discussion regarding additional content to CfRR.
