### ISSUE TITLE
UKBiobank/population scale data primer course

### ISSUE THREAD

**Issue by jh288** [coding-for-reproducible-research/CfRR_Courses#93]
The increase in availability of large population scale datasets such as UKBiobank and AllOfUs has highlighted a skills gap in the efficient manipulations and use of these data. it would be great to be able to offer a primer to introduce people to using these resources. The course could be timed to coincide with either the genomics masters or some other PG intake to make this an even more valuable resource.

**Comment by berrli** [comment]
@jh288 Thank you for creating this issue and the idea for the primer course. Ive moved this content into the new home for the proposal of additional workshops within the discussion [here](https://github.com/coding-for-reproducible-research/CfRR_Courses/discussions/84). Thank you for suggesting this course, and attending the community day, it was great to meet you!
