### ISSUE TITLE
Add info on licenses to Reproducibility page

### ISSUE THREAD

**Issue by amyheather** [coding-for-reproducible-research/CfRR_Courses#98]
[Content to be adapted](https://coding-for-reproducible-research.github.io/CfRR_Courses/individual_modules/software_development_best_practices/reproducibility.html)

## Suggestion

Add more information on choosing and including a license with your code - such as in the **Reproducibility** page as part of the Software Development Best Practices course.

## Extra notes

* Add a LICENSE file
* Great website for help in choosing a license: <https://choosealicense.com/>
* Emphasis on the fact that no-one would be able to reuse your code if a license is not included, so it is essential when you're trying to conduct reproducible research, that other researchers might be able to run, learn from and build on

**Comment by berrli** [comment]
Added with PR #116
